//! sdwan-core: shared type system for the control plane (P0).
//!
//! Scope is intentionally narrow: this crate defines the data model the agent and
//! the controller exchange over the wire and apply on-device. It has no I/O and no
//! dependencies on the existing data-plane crates (`sdwanlite-core`, `sdwanlite-lb`,
//! `sdwanlite-mesh`, `sdwanlite-bgp`, `sdwanlite-acme`, `sdwanlite-app`) — those
//! stay on the device data path and remain untouched by P0.
//!
//! ## Multi-tenancy
//!
//! Every configuration carries an [`DeviceConfig::org_id`] and
//! [`DeviceConfig::site_id`]; controllers MUST scope every query by `org_id` and
//! agents MUST refuse configs addressed to a different `org_id` than the one they
//! registered with.
//!
//! ## Transactional apply
//!
//! Configs are versioned (`DeviceConfig::version`, monotonically increasing per
//! device). Agents apply via snapshot → apply → verify → commit/rollback. A failed
//! verify rolls back to the previous version without bumping the version counter.
//!
//! ## Security
//!
//! Wire-private keys never appear in any struct (public keys only). Auth tokens are
//! passed around by the controller/agent via unlinked `0600` files at runtime, not
//! as argv (see AGENTS.md). Examples and doc-comments use RFC 5737 documentation
//! addresses (`192.0.2.x`, `198.51.100.x`, `203.0.113.x`) only — no real IPs.
//!
//! ## flexiWAN coverage in this crate
//!
//! - §1 Management Core → [`DeviceConfig::org_id`] / [`DeviceConfig::site_id`] (multi-tenant)
//! - §2 Device Config → [`DeviceConfig`] + version
//! - §10 Path Labels → [`PathLabel`]
//! - §11 Path Selection → [`TunnelConfig::WireGuard::path_label`] (declarative link)
//! - §9 Link Monitors → [`HealthCheckConfig`]
//!
//! Other flexiWAN groups (routing, NAT, QoS, HA, AI, dashboards, NB API) are
//! implemented in P1–P3 (see `docs/ARCHITECTURE-P0.md`).

#![deny(rust_2018_idioms)]
#![warn(missing_docs)]

use serde::{Deserialize, Serialize};
use std::net::IpAddr;
use uuid::Uuid;

/// Monotonic per-device configuration version.
///
/// The controller increments on every successful push; the agent keeps a `version` in
/// its own `DeviceConfig` and only accepts new configs where `new.version > current.version`
/// (optimistic locking). A failed verify does NOT bump the version.
pub type ConfigVersion = u64;

/// Logical underlay/overlay link class (flexiWAN §10 — Path Labels).
///
/// Path labels carry SLA expectations that the link monitor + path selection engine
/// later consume. They are deliberately side-effect-free here.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct PathLabel {
    /// Stable identifier (UUIDv4 generated by the controller).
    pub id: Uuid,

    /// Human-readable name (e.g. `MPLS-Primary`, `ISP1`, `LTE-Backup`).
    ///
    /// Unique within the org; agents use it to bind policies to interfaces.
    pub name: String,

    /// Link class.
    #[serde(rename = "type")]
    pub kind: PathLabelKind,

    /// SLA expectations (latency/jitter/loss/bw). Free-form for now; the P1 link-monitor
    /// crate will enforce them. Empty means "best effort".
    #[serde(default)]
    pub sla: String,
}

/// Physical/transport category of a path label.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PathLabelKind {
    /// MPLS / private backbone.
    Mpls,
    /// Public Internet (broadband).
    Internet,
    /// 5G mobile.
    #[serde(rename = "5g")]
    FiveG,
    /// Starlink / satellite.
    Starlink,
    /// LTE / 4G mobile.
    Lte,
    /// Generic other / not classified.
    Other,
}

/// Probing policy for a link (flexiWAN §9).
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct HealthCheckConfig {
    /// Probe cadence in milliseconds.
    #[serde(default = "default_hc_interval_ms")]
    pub interval_ms: u32,

    /// Probe transport.
    #[serde(default)]
    pub probe_type: ProbeType,

    /// Number of consecutive failures before the link is marked down.
    #[serde(default = "default_hc_threshold")]
    pub threshold: u32,

    /// Per-probe timeout in milliseconds.
    #[serde(default = "default_hc_timeout_ms")]
    pub timeout_ms: u32,
}

fn default_hc_interval_ms() -> u32 {
    1000
}
fn default_hc_threshold() -> u32 {
    3
}
fn default_hc_timeout_ms() -> u32 {
    500
}

/// Probe transport used by the link monitor.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProbeType {
    /// ICMP echo (requires `CAP_NET_RAW`; see AGENTS.md).
    #[default]
    Icmp,
    /// HTTP/HTTPS GET against a target URL.
    Http,
    /// DNS query against a resolver.
    Dns,
    /// TCP connect against a port.
    Tcp,
}

/// On-device logical interface declaration.
///
/// `name` matches the kernel interface label (e.g. `eth0`, `wg0`).
/// `addresses` use RFC 5737 documentation prefixes in examples; production values
/// come from the controller.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Interface {
    /// Kernel interface name.
    pub name: String,

    /// Stable addresses bound to the interface (IPv4/IPv6).
    pub addresses: Vec<IpAddr>,

    /// MTU in bytes (0 means kernel default).
    #[serde(default)]
    pub mtu: u16,

    /// Optional path-label binding (flexiWAN §10).
    #[serde(default)]
    pub path_label: Option<String>,
}

/// Tunnel configuration. Currently only WireGuard is supported; the enum is shaped
/// to make IPsec/SSTP a drop-in addition in P1.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum TunnelConfig {
    /// WireGuard overlay.
    WireGuard(WireGuardTunnel),
}

/// WireGuard-specific tunnel config.
///
/// `public_key` is the peer's *public* key (base64 X25519, 32 bytes). Private keys are
/// never exchanged via this struct — they are generated on-device and kept in
/// `0600` files only (see AGENTS.md).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct WireGuardTunnel {
    /// Tunnel interface name (e.g. `wg0`).
    pub interface: String,

    /// Path label this tunnel rides (must reference an existing label).
    pub path_label: String,

    /// Per-tunnel health probe.
    #[serde(default)]
    pub health_check: HealthCheckConfig,

    /// Endpoint address (RFC 5737 example: `203.0.113.7:51820`).
    pub endpoint: String,

    /// Allowed remote IPs for the peer's side of the tunnel.
    pub allowed_ips: Vec<IpAddr>,

    /// Base64 X25519 public key (44 chars including padding).
    pub public_key: String,
}

/// Static route entry.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Route {
    /// Destination prefix (CIDR).
    pub destination: String,

    /// Next-hop (interface name or IP).
    pub next_hop: String,

    /// Administrative distance (lower wins).
    #[serde(default = "default_metric")]
    pub metric: u32,
}

fn default_metric() -> u32 {
    100
}

/// Firewall policy (P0: skeleton, P1 wires the nftables render).
#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct FirewallPolicy {
    /// Ordered list of rules; first match wins.
    #[serde(default)]
    pub rules: Vec<FirewallRule>,
}

/// Single firewall rule (flexiWAN §7). First match in `FirewallPolicy.rules`
/// wins; rules with `None` match-conditions apply to any traffic.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct FirewallRule {
    /// Verdict on match.
    pub action: FirewallAction,
    /// Source CIDR/IP/iface (optional).
    #[serde(default)]
    pub source: Option<String>,
    /// Destination CIDR/IP/iface (optional).
    #[serde(default)]
    pub destination: Option<String>,
    /// L4 protocol (e.g. `tcp`, `udp`).
    #[serde(default)]
    pub protocol: Option<String>,
    /// L4 port (when applicable).
    #[serde(default)]
    pub port: Option<u16>,
    /// Free-form operator note.
    #[serde(default)]
    pub comment: Option<String>,
}

/// Firewall verdict (flexiWAN §7).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FirewallAction {
    /// Forward matching traffic.
    Accept,
    /// Drop silently.
    Drop,
    /// Reject with ICMP unreachable.
    Reject,
}

/// QoS policy (P0: skeleton, P1 wires HTB/TC).
#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct QosPolicy {
    /// Ordered QoS classes (top match wins).
    #[serde(default)]
    pub classes: Vec<QosClass>,
}

/// QoS class (flexiWAN §12). One row per traffic class; the controller
/// emits HTB/TC + DSCP rules from these.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct QosClass {
    /// Class name (e.g. `voip`, `data`).
    pub name: String,
    /// DSCP value 0-63.
    pub dscp: u8,
    /// Bandwidth ceiling in bits/second (0 = unlimited).
    #[serde(default)]
    pub bandwidth_bps: u64,
}

/// Full device configuration the controller pushes.
///
/// Optimistic-locking via `version`: an agent MUST refuse any `DeviceConfig` whose
/// `version` is not strictly greater than its own current version.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DeviceConfig {
    /// Device identity (UUIDv4 assigned at first registration).
    pub device_id: Uuid,

    /// Owning org (multi-tenant isolation boundary).
    pub org_id: Uuid,

    /// Site within the org (flexiWAN §1 — Org/Site/Device hierarchy).
    pub site_id: Uuid,

    /// Hostname reported by the device at registration.
    pub hostname: String,

    /// Logical interfaces on the device.
    pub interfaces: Vec<Interface>,

    /// Tunnels (currently WireGuard only).
    pub tunnels: Vec<TunnelConfig>,

    /// Static routes.
    pub routes: Vec<Route>,

    /// Firewall policy.
    pub firewall: FirewallPolicy,

    /// QoS policy.
    pub qos: QosPolicy,

    /// Path labels declared on this device.
    pub path_labels: Vec<PathLabel>,

    /// Monotonic version — bumped by the controller on every push.
    pub version: ConfigVersion,
}

impl DeviceConfig {
    /// Bump the version counter, returning a new config.
    ///
    /// Agents call this only inside the `commit` step of a successful transactional
    /// apply (see `sdwan-agent::Agent::apply_config`). Verify failure MUST NOT
    /// call this.
    pub fn with_bumped_version(mut self) -> Self {
        self.version = self.version.saturating_add(1);
        self
    }

    /// True iff `other.version > self.version`.
    pub fn is_strictly_newer_than(&self, other: &Self) -> bool {
        self.version > other.version
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> DeviceConfig {
        DeviceConfig {
            device_id: Uuid::new_v4(),
            org_id: Uuid::new_v4(),
            site_id: Uuid::new_v4(),
            hostname: "edge-01".into(),
            interfaces: vec![Interface {
                name: "eth0".into(),
                addresses: vec!["203.0.113.7".parse().unwrap()],
                mtu: 0,
                path_label: None,
            }],
            tunnels: vec![TunnelConfig::WireGuard(WireGuardTunnel {
                interface: "wg0".into(),
                path_label: "MPLS-Primary".into(),
                health_check: HealthCheckConfig {
                    interval_ms: 1000,
                    probe_type: ProbeType::Icmp,
                    threshold: 3,
                    timeout_ms: 500,
                },
                endpoint: "203.0.113.7:51820".into(),
                allowed_ips: vec!["198.51.100.10".parse().unwrap()],
                public_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=".into(),
            })],
            routes: vec![Route {
                destination: "0.0.0.0/0".into(),
                next_hop: "203.0.113.1".into(),
                metric: 100,
            }],
            firewall: FirewallPolicy::default(),
            qos: QosPolicy::default(),
            path_labels: vec![PathLabel {
                id: Uuid::new_v4(),
                name: "MPLS-Primary".into(),
                kind: PathLabelKind::Mpls,
                sla: "loss<0.1% rtt<10ms".into(),
            }],
            version: 1,
        }
    }

    #[test]
    fn version_bump_and_compare() {
        let c = sample();
        let c2 = c.clone().with_bumped_version();
        assert!(c2.is_strictly_newer_than(&c));
        assert!(!c.is_strictly_newer_than(&c2));
        assert_eq!(c2.version, c.version + 1);
    }

    #[test]
    fn json_roundtrip() {
        let c = sample();
        let j = serde_json::to_string(&c).unwrap();
        let back: DeviceConfig = serde_json::from_str(&j).unwrap();
        assert_eq!(back, c);
    }

    #[test]
    fn tunnel_tag_serde() {
        // Ensure the tagged enum produces stable, documented JSON.
        let j = r#"{"kind":"wire_guard","interface":"wg0","path_label":"X","health_check":{"interval_ms":1000,"probe_type":"icmp","threshold":3,"timeout_ms":500},"endpoint":"203.0.113.7:51820","allowed_ips":["198.51.100.1"],"public_key":"A"}"#;
        let t: TunnelConfig = serde_json::from_str(j).unwrap();
        match t {
            TunnelConfig::WireGuard(w) => {
                assert_eq!(w.interface, "wg0");
                assert_eq!(w.path_label, "X");
            }
        }
    }
}
