[package]
name = "sdwanlite-mesh"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sdwanlite-core = { path = "../core" }
x25519-dalek = { workspace = true }
base64 = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["process"] }
tracing = { workspace = true }
boringtun = { version = "0.7", default-features = false }

[dev-dependencies]
tokio = { workspace = true }
