[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/sdwan-core",
    "crates/sdwan-agent",
    "crates/lb",
    "crates/mesh",
    "crates/bgp",
    "crates/acme",
    "crates/app",
]
exclude = ["crates/web"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
thiserror = "1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.8"
x25519-dalek = { version = "2", features = ["static_secrets"] }
base64 = "0.22"
uuid = { version = "1", features = ["v4", "serde"] }
arc-swap = "1"
tokio-tungstenite = "0.24"
rusqlite = { version = "0.32", features = ["bundled"] }
axum-extra = { version = "0.9", features = ["ws"] }

[profile.release]
lto = true
strip = true
