[package]
name = "sdwanlite-lb"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sdwanlite-core = { path = "../core" }
tokio = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-pemfile = "2"

[dev-dependencies]
rcgen = "0.13"
tempfile = "3"
